package xentral

import (
	"context"
	"fmt"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"

	"lastsaas/internal/db"
	"lastsaas/internal/models"
)

// Engine executes bidirectional sync between Xentral and LastSaaS.
//
// Inbound (Xentral → LastSaaS): products, customers, suppliers, purchase orders, sales orders.
// Outbound (LastSaaS → Xentral): product EAN, product freefields.
// SPoT rules:
//   - lastEk (purchase price): LastSaaS is authoritative; Xentral value only used on first import.
//   - ean: LastSaaS is authoritative if already set (e.g. generated by EANRange).
//
// The XentralMapping collection is used as a join table so that repeated
// syncs update existing records rather than inserting duplicates.
type Engine struct {
	db *db.MongoDB
}

func NewEngine(database *db.MongoDB) *Engine {
	return &Engine{db: database}
}

// -------------------------------------------------------------------
// Products (Xentral articles → LastSaaS products)
// -------------------------------------------------------------------

func (e *Engine) SyncProducts(ctx context.Context, tenantID primitive.ObjectID, client *Client) models.XentralSyncLog {
	log := e.startLog(ctx, tenantID, "products")

	articles, err := client.ListArticles(ctx)
	if err != nil {
		return e.failLog(ctx, log, err.Error())
	}

	for _, a := range articles {
		if err := e.upsertProduct(ctx, tenantID, a); err != nil {
			log.Errors = append(log.Errors, fmt.Sprintf("%s: %v", a.ID, err))
			log.Skipped++
		} else {
			// distinguish create vs update via mapping existence check (already done in upsertProduct)
			log.Updated++
		}
	}

	return e.finishLog(ctx, log)
}

func (e *Engine) upsertProduct(ctx context.Context, tenantID primitive.ObjectID, a XArticle) error {
	if a.ID == "" || a.Name == "" {
		return nil // skip incomplete records
	}

	// Look up existing mapping
	var mapping models.XentralMapping
	err := e.db.XentralMappings().FindOne(ctx, bson.M{
		"tenantId":  tenantID,
		"entity":    "product",
		"xentralId": a.ID,
	}).Decode(&mapping)

	now := time.Now()
	articleNr := a.ResolvedArticleNumber()
	nameShort := truncate(a.Name, 45)
	if nameShort == "" {
		nameShort = truncate(articleNr, 45)
	}

	tags := resolveTagNames(a.Tags)
	attrs := resolveAttributes(a.ResolvedCharacteristics())
	active := !a.IsDisabled || a.Active

	freeFields := resolveFreeFields(a.FreeFields)

	if err == mongo.ErrNoDocuments {
		// Create new product
		product := models.Product{
			ID:          primitive.NewObjectID(),
			TenantID:    tenantID,
			NameShort:   nameShort,
			NameLong:    truncate(a.Name, 255),
			Description: a.Description,
			EAN:         truncate(a.EAN, 32),
			WeightKg:    a.ResolvedWeight(),
			LastEK:      a.ResolvedPurchasePrice(),
			LastVK:      a.ResolvedSellPrice(),
			Tags:        tags,
			Attributes:  attrs,
			XentralNr:   truncate(articleNr, 50),
			Active:      active,
			FreeFields:  freeFields,
			CreatedAt:   now,
			UpdatedAt:   now,
		}
		if _, err := e.db.Products().InsertOne(ctx, product); err != nil {
			return fmt.Errorf("insert product: %w", err)
		}
		_, _ = e.db.XentralMappings().InsertOne(ctx, models.XentralMapping{
			ID:        primitive.NewObjectID(),
			TenantID:  tenantID,
			Entity:    "product",
			LocalID:   product.ID,
			XentralID: a.ID,
			XentralNr: articleNr,
			CreatedAt: now,
			UpdatedAt: now,
		})
		return nil
	}
	if err != nil {
		return fmt.Errorf("lookup mapping: %w", err)
	}

	// Update existing product.
	// lastEk is our SPoT: never overwrite a price we've set ourselves.
	// ean is also ours: if a local EAN is already set (e.g. generated by our EANRange),
	// do not overwrite it with whatever Xentral has.
	// name, description, tags, attributes, active, xentralNr all reflect Xentral (SPoT).
	setFields := bson.M{
		"nameShort":   nameShort,
		"nameLong":    truncate(a.Name, 255),
		"description": a.Description,
		"weightKg":    a.ResolvedWeight(),
		"tags":        tags,
		"attributes":  attrs,
		"xentralNr":   truncate(articleNr, 50),
		"active":      active,
		"freeFields":  freeFields,
		"updatedAt":   now,
	}

	// Fetch current product to check whether EAN / lastEk / lastVk are already set
	var existing struct {
		EAN    string  `bson:"ean"`
		LastEK float64 `bson:"lastEk"`
		LastVK float64 `bson:"lastVk"`
	}
	_ = e.db.Products().FindOne(ctx, bson.M{"_id": mapping.LocalID}).Decode(&existing)

	purchasePrice := a.ResolvedPurchasePrice()
	sellPrice := a.ResolvedSellPrice()
	if existing.EAN == "" && a.EAN != "" {
		setFields["ean"] = truncate(a.EAN, 32)
	}
	if existing.LastEK == 0 && purchasePrice > 0 {
		setFields["lastEk"] = purchasePrice
	}
	if existing.LastVK == 0 && sellPrice > 0 {
		setFields["lastVk"] = sellPrice
	}

	_, _ = e.db.Products().UpdateOne(ctx,
		bson.M{"_id": mapping.LocalID, "tenantId": tenantID},
		bson.M{"$set": setFields},
	)
	_, _ = e.db.XentralMappings().UpdateOne(ctx,
		bson.M{"_id": mapping.ID},
		bson.M{"$set": bson.M{"xentralNr": articleNr, "updatedAt": now}},
	)
	return nil
}

// -------------------------------------------------------------------
// Customers (Xentral customers → LastSaaS customers)
// -------------------------------------------------------------------

func (e *Engine) SyncCustomers(ctx context.Context, tenantID primitive.ObjectID, client *Client) models.XentralSyncLog {
	log := e.startLog(ctx, tenantID, "customers")

	customers, err := client.ListCustomers(ctx)
	if err != nil {
		return e.failLog(ctx, log, err.Error())
	}

	for _, c := range customers {
		if err := e.upsertCustomer(ctx, tenantID, c); err != nil {
			log.Errors = append(log.Errors, fmt.Sprintf("%s: %v", c.ID, err))
			log.Skipped++
		} else {
			log.Updated++
		}
	}

	return e.finishLog(ctx, log)
}

func (e *Engine) upsertCustomer(ctx context.Context, tenantID primitive.ObjectID, xc XCustomer) error {
	if xc.ID == "" {
		return nil
	}
	company := xc.ResolvedCompany()
	if company == "" {
		return fmt.Errorf("no company/name in response")
	}

	var mapping models.XentralMapping
	err := e.db.XentralMappings().FindOne(ctx, bson.M{
		"tenantId":  tenantID,
		"entity":    "customer",
		"xentralId": xc.ID,
	}).Decode(&mapping)

	now := time.Now()
	ra := xc.ResolvedAddress()
	addr := models.CustomerAddress{
		Street:  ra.Street,
		City:    ra.City,
		Zip:     ra.ResolvedZip(),
		Country: ra.Country,
	}

	if err == mongo.ErrNoDocuments {
		customer := models.Customer{
			ID:        primitive.NewObjectID(),
			TenantID:  tenantID,
			Company:   truncate(company, 200),
			Firstname: truncate(xc.FirstName, 50),
			Lastname:  truncate(xc.LastName, 50),
			Email:     truncate(xc.Email, 120),
			Phone:     truncate(xc.Phone, 50),
			Address:   addr,
			CreatedAt: now,
			UpdatedAt: now,
		}
		if _, err := e.db.Customers().InsertOne(ctx, customer); err != nil {
			return fmt.Errorf("insert customer: %w", err)
		}
		_, _ = e.db.XentralMappings().InsertOne(ctx, models.XentralMapping{
			ID:        primitive.NewObjectID(),
			TenantID:  tenantID,
			Entity:    "customer",
			LocalID:   customer.ID,
			XentralID: xc.ID,
			XentralNr: xc.CustomerNumber,
			CreatedAt: now,
			UpdatedAt: now,
		})
		return nil
	}
	if err != nil {
		return fmt.Errorf("lookup mapping: %w", err)
	}

	_, _ = e.db.Customers().UpdateOne(ctx,
		bson.M{"_id": mapping.LocalID, "tenantId": tenantID},
		bson.M{"$set": bson.M{
			"company":   truncate(company, 200),
			"firstname": truncate(xc.FirstName, 50),
			"lastname":  truncate(xc.LastName, 50),
			"email":     truncate(xc.Email, 120),
			"phone":     truncate(xc.Phone, 50),
			"address":   addr,
			"updatedAt": now,
		}},
	)
	return nil
}

// -------------------------------------------------------------------
// Suppliers (Xentral suppliers → LastSaaS suppliers)
// -------------------------------------------------------------------

func (e *Engine) SyncSuppliers(ctx context.Context, tenantID primitive.ObjectID, client *Client) models.XentralSyncLog {
	log := e.startLog(ctx, tenantID, "suppliers")

	suppliers, err := client.ListSuppliers(ctx)
	if err != nil {
		return e.failLog(ctx, log, err.Error())
	}

	for _, s := range suppliers {
		if err := e.upsertSupplier(ctx, tenantID, s); err != nil {
			log.Errors = append(log.Errors, fmt.Sprintf("%s: %v", s.ID, err))
			log.Skipped++
		} else {
			log.Updated++
		}
	}

	return e.finishLog(ctx, log)
}

func (e *Engine) upsertSupplier(ctx context.Context, tenantID primitive.ObjectID, xs XSupplier) error {
	if xs.ID == "" {
		return nil
	}
	company := xs.ResolvedCompany()
	if company == "" {
		return fmt.Errorf("no company/name in response")
	}

	var mapping models.XentralMapping
	err := e.db.XentralMappings().FindOne(ctx, bson.M{
		"tenantId":  tenantID,
		"entity":    "supplier",
		"xentralId": xs.ID,
	}).Decode(&mapping)

	now := time.Now()

	if err == mongo.ErrNoDocuments {
		supplier := models.Supplier{
			ID:        primitive.NewObjectID(),
			TenantID:  tenantID,
			Company:   truncate(company, 200),
			Firstname: truncate(xs.FirstName, 50),
			Lastname:  truncate(xs.LastName, 50),
			Email:     truncate(xs.Email, 120),
			Origin:    truncate(xs.Origin, 50),
			CreatedAt: now,
			UpdatedAt: now,
		}
		if _, err := e.db.Suppliers().InsertOne(ctx, supplier); err != nil {
			return fmt.Errorf("insert supplier: %w", err)
		}
		_, _ = e.db.XentralMappings().InsertOne(ctx, models.XentralMapping{
			ID:        primitive.NewObjectID(),
			TenantID:  tenantID,
			Entity:    "supplier",
			LocalID:   supplier.ID,
			XentralID: xs.ID,
			XentralNr: xs.SupplierNumber,
			CreatedAt: now,
			UpdatedAt: now,
		})
		return nil
	}
	if err != nil {
		return fmt.Errorf("lookup mapping: %w", err)
	}

	_, _ = e.db.Suppliers().UpdateOne(ctx,
		bson.M{"_id": mapping.LocalID, "tenantId": tenantID},
		bson.M{"$set": bson.M{
			"company":   truncate(company, 200),
			"firstname": truncate(xs.FirstName, 50),
			"lastname":  truncate(xs.LastName, 50),
			"email":     truncate(xs.Email, 120),
			"origin":    truncate(xs.Origin, 50),
			"updatedAt": now,
		}},
	)
	return nil
}

// -------------------------------------------------------------------
// Orders (Xentral purchaseOrders v3 → LastSaaS orders)
// -------------------------------------------------------------------

func (e *Engine) SyncOrders(ctx context.Context, tenantID primitive.ObjectID, client *Client) models.XentralSyncLog {
	log := e.startLog(ctx, tenantID, "orders")

	orders, err := client.ListPurchaseOrders(ctx)
	if err != nil {
		return e.failLog(ctx, log, err.Error())
	}

	for _, o := range orders {
		if err := e.upsertOrder(ctx, tenantID, o, client); err != nil {
			log.Errors = append(log.Errors, fmt.Sprintf("%s: %v", o.ID, err))
			log.Skipped++
		} else {
			log.Updated++
		}
	}

	return e.finishLog(ctx, log)
}

// resolveSupplierID looks up the local SupplierID for a Xentral supplier ID via the mappings table.
func (e *Engine) resolveSupplierID(ctx context.Context, tenantID primitive.ObjectID, xentralSupplierID string) *primitive.ObjectID {
	if xentralSupplierID == "" {
		return nil
	}
	var m models.XentralMapping
	err := e.db.XentralMappings().FindOne(ctx, bson.M{
		"tenantId":  tenantID,
		"entity":    "supplier",
		"xentralId": xentralSupplierID,
	}).Decode(&m)
	if err != nil {
		return nil
	}
	return &m.LocalID
}

// resolveProductID looks up the local ProductID for a Xentral article ID via the mappings table.
func (e *Engine) resolveProductID(ctx context.Context, tenantID primitive.ObjectID, xentralArticleID string) *primitive.ObjectID {
	if xentralArticleID == "" {
		return nil
	}
	var m models.XentralMapping
	err := e.db.XentralMappings().FindOne(ctx, bson.M{
		"tenantId":  tenantID,
		"entity":    "product",
		"xentralId": xentralArticleID,
	}).Decode(&m)
	if err != nil {
		return nil
	}
	return &m.LocalID
}

func (e *Engine) upsertOrder(ctx context.Context, tenantID primitive.ObjectID, xo XPurchaseOrder, client *Client) error {
	if xo.ID == "" {
		return nil
	}

	// Fetch line items via separate endpoint – the v3 list response does not include them.
	if items, err := client.ListPurchaseOrderLineItems(ctx, xo.ID); err == nil && len(items) > 0 {
		xo.LineItems = items
	}

	var mapping models.XentralMapping
	err := e.db.XentralMappings().FindOne(ctx, bson.M{
		"tenantId":  tenantID,
		"entity":    "order",
		"xentralId": xo.ID,
	}).Decode(&mapping)

	now := time.Now()

	// Resolve order date from Xentral. Try ISO date first, then datetime prefix.
	orderDate := now
	if d := xo.ResolvedDate(); d != "" {
		for _, layout := range []string{"2006-01-02T15:04:05Z", "2006-01-02T15:04:05", "2006-01-02"} {
			if t, parseErr := time.Parse(layout, d); parseErr == nil {
				orderDate = t
				break
			}
		}
	}

	// Resolve supplier via mapping (requires suppliers sync to have run first).
	// The v3 API stores the supplier as address.id; use ResolvedSupplierID() to handle both formats.
	supplierID := e.resolveSupplierID(ctx, tenantID, xo.ResolvedSupplierID())

	// Build order products from ALL line items.
	// ProductID is optional: items imported before the products sync runs still carry
	// XentralArticleID so they can be resolved on the next sync pass.
	var orderProducts []models.OrderProduct
	for _, item := range xo.LineItems {
		qty := int(item.Quantity)
		if qty < 1 {
			qty = 1
		}
		op := models.OrderProduct{
			XentralArticleID:     item.Article.ID,
			XentralArticleNumber: item.Article.ArticleNumber,
			Description:          item.Description,
			Quantity:             qty,
			UnitPriceUSD:         item.UnitPrice,
			TotalPriceUSD:        item.UnitPrice * float64(qty),
		}
		if pid := e.resolveProductID(ctx, tenantID, item.Article.ID); pid != nil {
			op.ProductID = pid
		}
		orderProducts = append(orderProducts, op)
	}

	currency := xo.ResolvedCurrency()
	orderNumber := xo.ResolvedOrderNumber()
	totalNet := xo.ResolvedTotalNet()
	orderUserDefs := mapFreifelderToUserDefs(xo.ResolvedFreifelder())

	if err == mongo.ErrNoDocuments {
		order := models.Order{
			ID:          primitive.NewObjectID(),
			TenantID:    tenantID,
			SupplierID:  supplierID,
			OrderNumber: orderNumber,
			OrderDate:   orderDate,
			Currency:    currency,
			OrderSumUSD: totalNet,
			Products:    orderProducts,
			UserDef01:   orderUserDefs[0],
			UserDef02:   orderUserDefs[1],
			UserDef03:   orderUserDefs[2],
			UserDef04:   orderUserDefs[3],
			UserDef05:   orderUserDefs[4],
			UserDef06:   orderUserDefs[5],
			UserDef07:   orderUserDefs[6],
			UserDef08:   orderUserDefs[7],
			UserDef09:   orderUserDefs[8],
			UserDef10:   orderUserDefs[9],
			CreatedAt:   now,
			UpdatedAt:   now,
		}
		if _, insertErr := e.db.Orders().InsertOne(ctx, order); insertErr != nil {
			return fmt.Errorf("insert order: %w", insertErr)
		}
		_, _ = e.db.XentralMappings().InsertOne(ctx, models.XentralMapping{
			ID:        primitive.NewObjectID(),
			TenantID:  tenantID,
			Entity:    "order",
			LocalID:   order.ID,
			XentralID: xo.ID,
			XentralNr: orderNumber,
			CreatedAt: now,
			UpdatedAt: now,
		})
		return nil
	}
	if err != nil {
		return fmt.Errorf("lookup mapping: %w", err)
	}

	setFields := bson.M{
		"orderSumUsd": totalNet,
		"currency":    currency,
		"orderDate":   orderDate,
		"userDef01":   orderUserDefs[0],
		"userDef02":   orderUserDefs[1],
		"userDef03":   orderUserDefs[2],
		"userDef04":   orderUserDefs[3],
		"userDef05":   orderUserDefs[4],
		"userDef06":   orderUserDefs[5],
		"userDef07":   orderUserDefs[6],
		"userDef08":   orderUserDefs[7],
		"userDef09":   orderUserDefs[8],
		"userDef10":   orderUserDefs[9],
		"updatedAt":   now,
	}
	if supplierID != nil {
		setFields["supplierId"] = supplierID
	}
	// Only overwrite line items when Xentral actually returned some.
	// If the list endpoint omits lineItems (e.g. large response truncation or API version
	// differences), we keep whatever we already have rather than wiping existing data.
	if len(orderProducts) > 0 {
		setFields["products"] = orderProducts
	}
	_, _ = e.db.Orders().UpdateOne(ctx,
		bson.M{"_id": mapping.LocalID, "tenantId": tenantID},
		bson.M{"$set": setFields},
	)
	return nil
}

// -------------------------------------------------------------------
// Sales Orders (Xentral salesOrders v3 → LastSaaS sales_orders)
// These are inbound/outbound sales to customers; used for reorder planning.
// -------------------------------------------------------------------

func (e *Engine) SyncSalesOrders(ctx context.Context, tenantID primitive.ObjectID, client *Client) models.XentralSyncLog {
	log := e.startLog(ctx, tenantID, "sales_orders")

	orders, err := client.ListSalesOrders(ctx)
	if err != nil {
		return e.failLog(ctx, log, err.Error())
	}

	for _, o := range orders {
		if err := e.upsertSalesOrder(ctx, tenantID, o); err != nil {
			log.Errors = append(log.Errors, fmt.Sprintf("%s: %v", o.ID, err))
			log.Skipped++
		} else {
			log.Updated++
		}
	}

	return e.finishLog(ctx, log)
}

func (e *Engine) upsertSalesOrder(ctx context.Context, tenantID primitive.ObjectID, xo XSalesOrder) error {
	if xo.ID == "" {
		return nil
	}

	var mapping models.XentralMapping
	err := e.db.XentralMappings().FindOne(ctx, bson.M{
		"tenantId":  tenantID,
		"entity":    "sales_order",
		"xentralId": xo.ID,
	}).Decode(&mapping)

	now := time.Now()

	orderDate := now
	if xo.Date != "" {
		if t, parseErr := time.Parse("2006-01-02", xo.Date); parseErr == nil {
			orderDate = t
		}
	}

	customerID := e.resolveCustomerID(ctx, tenantID, xo.Customer.ID)

	var lineItems []models.SalesOrderLineItem
	for _, item := range xo.LineItems {
		li := models.SalesOrderLineItem{
			XentralArticleID: item.Article.ID,
			Description:      item.Description,
			Quantity:         item.Quantity,
			UnitPriceEUR:     item.UnitPrice,
			TotalPriceEUR:    item.UnitPrice * item.Quantity,
		}
		if pid := e.resolveProductID(ctx, tenantID, item.Article.ID); pid != nil {
			li.ProductID = pid
		}
		lineItems = append(lineItems, li)
	}

	netSales := xo.NetSales.Float64()
	total := xo.Total.Float64()
	currency := xo.Currency
	if currency == "" {
		currency = xo.NetSales.Currency
	}
	soUserDefs := mapFreifelderToUserDefs(xo.ResolvedFreifelder())

	if err == mongo.ErrNoDocuments {
		so := models.SalesOrder{
			ID:                primitive.NewObjectID(),
			TenantID:          tenantID,
			CustomerID:        customerID,
			XentralDocumentNr: xo.DocumentNumber,
			ExternalOrderNr:   xo.ExternalOrderNumber,
			Date:              orderDate,
			Status:            xo.Status,
			LineItems:         lineItems,
			TotalNetEUR:       netSales,
			TotalGrossEUR:     total,
			Currency:          currency,
			UserDef01:         soUserDefs[0],
			UserDef02:         soUserDefs[1],
			UserDef03:         soUserDefs[2],
			UserDef04:         soUserDefs[3],
			UserDef05:         soUserDefs[4],
			UserDef06:         soUserDefs[5],
			UserDef07:         soUserDefs[6],
			UserDef08:         soUserDefs[7],
			UserDef09:         soUserDefs[8],
			UserDef10:         soUserDefs[9],
			CreatedAt:         now,
			UpdatedAt:         now,
		}
		if _, insertErr := e.db.SalesOrders().InsertOne(ctx, so); insertErr != nil {
			return fmt.Errorf("insert sales order: %w", insertErr)
		}
		_, _ = e.db.XentralMappings().InsertOne(ctx, models.XentralMapping{
			ID:        primitive.NewObjectID(),
			TenantID:  tenantID,
			Entity:    "sales_order",
			LocalID:   so.ID,
			XentralID: xo.ID,
			XentralNr: xo.DocumentNumber,
			CreatedAt: now,
			UpdatedAt: now,
		})
		return nil
	}
	if err != nil {
		return fmt.Errorf("lookup mapping: %w", err)
	}

	setFields := bson.M{
		"status":        xo.Status,
		"totalNetEur":   netSales,
		"totalGrossEur": total,
		"userDef01":     soUserDefs[0],
		"userDef02":     soUserDefs[1],
		"userDef03":     soUserDefs[2],
		"userDef04":     soUserDefs[3],
		"userDef05":     soUserDefs[4],
		"userDef06":     soUserDefs[5],
		"userDef07":     soUserDefs[6],
		"userDef08":     soUserDefs[7],
		"userDef09":     soUserDefs[8],
		"userDef10":     soUserDefs[9],
		"updatedAt":     now,
	}
	if customerID != nil {
		setFields["customerId"] = customerID
	}
	if len(lineItems) > 0 {
		setFields["lineItems"] = lineItems
	}
	_, _ = e.db.SalesOrders().UpdateOne(ctx,
		bson.M{"_id": mapping.LocalID, "tenantId": tenantID},
		bson.M{"$set": setFields},
	)
	return nil
}

// -------------------------------------------------------------------
// Purchase Prices (Xentral /api/v1/purchasePrices → ProductPriceList Type=EK)
//
// SPoT rule: entries with Source="order" are never overwritten — those are
// derived from our own purchase order EK calculation (incl. freight).
// Xentral prices land as Source="import" and can be updated freely.
// -------------------------------------------------------------------

func (e *Engine) SyncPurchasePrices(ctx context.Context, tenantID primitive.ObjectID, client *Client) models.XentralSyncLog {
	log := e.startLog(ctx, tenantID, "purchase_prices")

	prices, err := client.ListPurchasePrices(ctx)
	if err != nil {
		return e.failLog(ctx, log, err.Error())
	}

	for _, p := range prices {
		if err := e.upsertPurchasePrice(ctx, tenantID, p); err != nil {
			log.Errors = append(log.Errors, fmt.Sprintf("%s: %v", p.ID, err))
			log.Skipped++
		} else {
			log.Updated++
		}
	}
	return e.finishLog(ctx, log)
}

func (e *Engine) upsertPurchasePrice(ctx context.Context, tenantID primitive.ObjectID, xp XPurchasePrice) error {
	if xp.ID == "" || xp.Product.ID == "" {
		return nil
	}

	productID := e.resolveProductID(ctx, tenantID, xp.Product.ID)
	if productID == nil {
		return nil // product not synced yet; skip silently
	}

	supplierID := e.resolveSupplierID(ctx, tenantID, xp.Supplier.ID)

	currency := xp.ResolvedCurrency()
	name := xp.Name
	if name == "" {
		name = "Xentral EK"
	}
	qty := int(xp.FromQuantity)
	if qty < 0 {
		qty = 0
	}

	now := time.Now()
	validFrom := parseDate(xp.ValidFrom)
	validTo := parseDate(xp.ExpiresAt)

	var mapping models.XentralMapping
	err := e.db.XentralMappings().FindOne(ctx, bson.M{
		"tenantId":  tenantID,
		"entity":    "purchase_price",
		"xentralId": xp.ID,
	}).Decode(&mapping)

	resolvedPrice := xp.ResolvedPrice()

	if err == mongo.ErrNoDocuments {
		entry := models.ProductPriceList{
			ID:         primitive.NewObjectID(),
			TenantID:   tenantID,
			ProductID:  *productID,
			SupplierID: supplierID,
			Type:       "EK",
			Name:       name,
			Price:      resolvedPrice,
			Currency:   currency,
			Quantity:   qty,
			ValidFrom:  validFrom,
			ValidTo:    validTo,
			Source:     "import",
			CreatedAt:  now,
			UpdatedAt:  now,
		}
		if _, insertErr := e.db.ProductPriceLists().InsertOne(ctx, entry); insertErr != nil {
			return fmt.Errorf("insert purchase price: %w", insertErr)
		}
		_, _ = e.db.XentralMappings().InsertOne(ctx, models.XentralMapping{
			ID:        primitive.NewObjectID(),
			TenantID:  tenantID,
			Entity:    "purchase_price",
			LocalID:   entry.ID,
			XentralID: xp.ID,
			CreatedAt: now,
			UpdatedAt: now,
		})
		// Also seed Product.lastEK if it is not yet set and this is a base price (qty=0).
		if resolvedPrice > 0 && qty == 0 {
			_, _ = e.db.Products().UpdateOne(ctx,
				bson.M{"_id": *productID, "tenantId": tenantID, "lastEk": bson.M{"$in": bson.A{nil, 0}}},
				bson.M{"$set": bson.M{"lastEk": resolvedPrice, "updatedAt": now}},
			)
		}
		return nil
	}
	if err != nil {
		return fmt.Errorf("lookup mapping: %w", err)
	}

	// Never overwrite entries with Source="order" – those are from our own EK calculation.
	var existing models.ProductPriceList
	if findErr := e.db.ProductPriceLists().FindOne(ctx, bson.M{"_id": mapping.LocalID}).Decode(&existing); findErr == nil {
		if existing.Source == "order" {
			return nil
		}
	}

	setFields := bson.M{
		"price":     resolvedPrice,
		"currency":  currency,
		"name":      name,
		"quantity":  qty,
		"updatedAt": now,
	}
	if validFrom != nil {
		setFields["validFrom"] = validFrom
	}
	if validTo != nil {
		setFields["validTo"] = validTo
	}
	if supplierID != nil {
		setFields["supplierId"] = supplierID
	}
	_, _ = e.db.ProductPriceLists().UpdateOne(ctx,
		bson.M{"_id": mapping.LocalID, "tenantId": tenantID},
		bson.M{"$set": setFields},
	)
	// Keep Product.lastEK in sync with the Xentral base price if it is not yet set.
	if resolvedPrice > 0 && qty == 0 {
		_, _ = e.db.Products().UpdateOne(ctx,
			bson.M{"_id": *productID, "tenantId": tenantID, "lastEk": bson.M{"$in": bson.A{nil, 0}}},
			bson.M{"$set": bson.M{"lastEk": resolvedPrice, "updatedAt": now}},
		)
	}
	return nil
}

// -------------------------------------------------------------------
// Sales Prices (Xentral /api/v3/salesPrices → ProductPriceList Type=VK)
// -------------------------------------------------------------------

func (e *Engine) SyncSalesPrices(ctx context.Context, tenantID primitive.ObjectID, client *Client) models.XentralSyncLog {
	log := e.startLog(ctx, tenantID, "sales_prices")

	prices, err := client.ListSalesPrices(ctx)
	if err != nil {
		return e.failLog(ctx, log, err.Error())
	}

	for _, p := range prices {
		if err := e.upsertSalesPrice(ctx, tenantID, p); err != nil {
			log.Errors = append(log.Errors, fmt.Sprintf("%s: %v", p.ID, err))
			log.Skipped++
		} else {
			log.Updated++
		}
	}
	return e.finishLog(ctx, log)
}

func (e *Engine) upsertSalesPrice(ctx context.Context, tenantID primitive.ObjectID, xp XSalesPrice) error {
	if xp.ID == "" || xp.Article.ID == "" {
		return nil
	}

	productID := e.resolveProductID(ctx, tenantID, xp.Article.ID)
	if productID == nil {
		return nil
	}

	price := xp.ResolvedPrice()
	currency := xp.Currency
	if currency == "" {
		currency = "EUR"
	}
	name := xp.Name
	if name == "" {
		name = "Xentral VK"
	}
	qty := int(xp.FromQuantity)
	if qty < 0 {
		qty = 0
	}

	now := time.Now()
	validFrom := parseDate(xp.ValidFrom)
	validTo := parseDate(xp.ValidTo)

	var mapping models.XentralMapping
	err := e.db.XentralMappings().FindOne(ctx, bson.M{
		"tenantId":  tenantID,
		"entity":    "sales_price",
		"xentralId": xp.ID,
	}).Decode(&mapping)

	if err == mongo.ErrNoDocuments {
		entry := models.ProductPriceList{
			ID:             primitive.NewObjectID(),
			TenantID:       tenantID,
			ProductID:      *productID,
			Type:           "VK",
			Name:           name,
			PriceGroupName: xp.Name,
			Price:          price,
			Currency:       currency,
			Quantity:       qty,
			ValidFrom:      validFrom,
			ValidTo:        validTo,
			Source:         "import",
			CreatedAt:      now,
			UpdatedAt:      now,
		}
		if _, insertErr := e.db.ProductPriceLists().InsertOne(ctx, entry); insertErr != nil {
			return fmt.Errorf("insert sales price: %w", insertErr)
		}
		_, _ = e.db.XentralMappings().InsertOne(ctx, models.XentralMapping{
			ID:        primitive.NewObjectID(),
			TenantID:  tenantID,
			Entity:    "sales_price",
			LocalID:   entry.ID,
			XentralID: xp.ID,
			XentralNr: xp.Name,
			CreatedAt: now,
			UpdatedAt: now,
		})
		return nil
	}
	if err != nil {
		return fmt.Errorf("lookup mapping: %w", err)
	}

	setFields := bson.M{
		"price":          price,
		"currency":       currency,
		"name":           name,
		"priceGroupName": xp.Name,
		"quantity":       qty,
		"updatedAt":      now,
	}
	if validFrom != nil {
		setFields["validFrom"] = validFrom
	}
	if validTo != nil {
		setFields["validTo"] = validTo
	}
	_, _ = e.db.ProductPriceLists().UpdateOne(ctx,
		bson.M{"_id": mapping.LocalID, "tenantId": tenantID},
		bson.M{"$set": setFields},
	)
	return nil
}

// parseDate parses an ISO date string "2006-01-02" into a *time.Time.
// Returns nil if the string is empty or unparseable.
func parseDate(s string) *time.Time {
	if s == "" {
		return nil
	}
	t, err := time.Parse("2006-01-02", s)
	if err != nil {
		return nil
	}
	return &t
}

// -------------------------------------------------------------------
// Push Purchase Orders (LastSaaS → Xentral)
//
// LastSaaS is the SPoT for purchase orders.
// PushOrderToXentral is called after every create/update of an Order.
// PushAllOrdersToXentral is used for initial setup or manual full re-sync.
// -------------------------------------------------------------------

// PushOrderToXentral creates or patches a single order in Xentral.
// Returns the Xentral purchase order ID.
func (e *Engine) PushOrderToXentral(ctx context.Context, tenantID, orderID primitive.ObjectID, client *Client) (string, error) {
	var order models.Order
	if err := e.db.Orders().FindOne(ctx, bson.M{"_id": orderID, "tenantId": tenantID}).Decode(&order); err != nil {
		return "", fmt.Errorf("load order: %w", err)
	}

	// Resolve Xentral supplier ID
	xSupplierID := e.resolveXentralID(ctx, tenantID, "supplier", order.SupplierID)
	if xSupplierID == "" {
		return "", fmt.Errorf("supplier not mapped to Xentral – sync suppliers first")
	}

	dateStr := order.OrderDate.Format("2006-01-02")
	notes := order.Misc
	if order.OrderContents != "" {
		if notes != "" {
			notes = order.OrderContents + "\n" + notes
		} else {
			notes = order.OrderContents
		}
	}

	// Build line items (only those with a mapped Xentral article)
	var lineItems []XPOLineItemCreate
	for _, p := range order.Products {
		xArticleID := e.resolveXentralID(ctx, tenantID, "product", p.ProductID)
		if xArticleID == "" {
			continue // skip unmapped products
		}
		lineItems = append(lineItems, XPOLineItemCreate{
			Article:   XPORef{ID: xArticleID},
			Quantity:  float64(p.Quantity),
			UnitPrice: p.UnitPriceUSD,
		})
	}

	// Check if this order already exists in Xentral
	var mapping models.XentralMapping
	err := e.db.XentralMappings().FindOne(ctx, bson.M{
		"tenantId": tenantID,
		"entity":   "order",
		"localId":  orderID,
	}).Decode(&mapping)

	now := time.Now()

	if err == mongo.ErrNoDocuments {
		// CREATE in Xentral
		xentralID, createErr := client.CreatePurchaseOrder(ctx, XPOCreateRequest{
			Supplier:  XPORef{ID: xSupplierID},
			Date:      dateStr,
			Notes:     notes,
			LineItems: lineItems,
		})
		if createErr != nil {
			return "", fmt.Errorf("create in Xentral: %w", createErr)
		}
		_, _ = e.db.XentralMappings().InsertOne(ctx, models.XentralMapping{
			ID:        primitive.NewObjectID(),
			TenantID:  tenantID,
			Entity:    "order",
			LocalID:   orderID,
			XentralID: xentralID,
			XentralNr: order.OrderNumber,
			CreatedAt: now,
			UpdatedAt: now,
		})
		return xentralID, nil
	}
	if err != nil {
		return "", fmt.Errorf("lookup mapping: %w", err)
	}

	// PATCH header in Xentral (line items are not patched to avoid overwriting
	// Xentral-side changes; use the manual sync for a full refresh)
	if patchErr := client.PatchPurchaseOrder(ctx, mapping.XentralID, XPOPatchRequest{
		Date:  dateStr,
		Notes: notes,
	}); patchErr != nil {
		return "", fmt.Errorf("patch in Xentral: %w", patchErr)
	}
	_, _ = e.db.XentralMappings().UpdateOne(ctx,
		bson.M{"_id": mapping.ID},
		bson.M{"$set": bson.M{"xentralNr": order.OrderNumber, "updatedAt": now}},
	)
	return mapping.XentralID, nil
}

// PushAllOrdersToXentral pushes all orders for the tenant that are not yet in Xentral,
// and patches those that are. Used for initial setup and scheduled full re-sync.
func (e *Engine) PushAllOrdersToXentral(ctx context.Context, tenantID primitive.ObjectID, client *Client) models.XentralSyncLog {
	log := e.startLog(ctx, tenantID, "push_orders")

	cursor, err := e.db.Orders().Find(ctx, bson.M{"tenantId": tenantID})
	if err != nil {
		return e.failLog(ctx, log, err.Error())
	}
	var orders []models.Order
	_ = cursor.All(ctx, &orders)

	for _, o := range orders {
		if _, pushErr := e.PushOrderToXentral(ctx, tenantID, o.ID, client); pushErr != nil {
			log.Errors = append(log.Errors, fmt.Sprintf("%s: %v", o.ID.Hex(), pushErr))
			log.Skipped++
		} else {
			log.Updated++
		}
	}
	return e.finishLog(ctx, log)
}

// resolveXentralID returns the Xentral UUID for a local ObjectID via the mappings table.
// entity: "product", "supplier", "customer", etc.
// Returns "" if not mapped.
func (e *Engine) resolveXentralID(ctx context.Context, tenantID primitive.ObjectID, entity string, localID *primitive.ObjectID) string {
	if localID == nil || *localID == (primitive.ObjectID{}) {
		return ""
	}
	var m models.XentralMapping
	err := e.db.XentralMappings().FindOne(ctx, bson.M{
		"tenantId": tenantID,
		"entity":   entity,
		"localId":  localID,
	}).Decode(&m)
	if err != nil {
		return ""
	}
	return m.XentralID
}

// resolveCustomerID looks up the local CustomerID for a Xentral customer ID.
func (e *Engine) resolveCustomerID(ctx context.Context, tenantID primitive.ObjectID, xentralCustomerID string) *primitive.ObjectID {
	if xentralCustomerID == "" {
		return nil
	}
	var m models.XentralMapping
	err := e.db.XentralMappings().FindOne(ctx, bson.M{
		"tenantId":  tenantID,
		"entity":    "customer",
		"xentralId": xentralCustomerID,
	}).Decode(&m)
	if err != nil {
		return nil
	}
	return &m.LocalID
}

// -------------------------------------------------------------------
// Scheduler
// -------------------------------------------------------------------

// RunScheduler starts a background goroutine that triggers auto-sync
// for all enabled tenants according to their configured SyncIntervalH.
// Call once from main; returns a stop function.
func RunScheduler(ctx context.Context, database *db.MongoDB) {
	go func() {
		ticker := time.NewTicker(30 * time.Minute)
		defer ticker.Stop()
		for {
			select {
			case <-ctx.Done():
				return
			case <-ticker.C:
				runScheduledSyncs(ctx, database)
			}
		}
	}()
}

func runScheduledSyncs(ctx context.Context, database *db.MongoDB) {
	cursor, err := database.XentralConfigs().Find(ctx, bson.M{
		"enabled":       true,
		"syncIntervalH": bson.M{"$gt": 0},
	}, options.Find().SetProjection(bson.M{
		"tenantId": 1, "baseUrl": 1, "apiToken": 1,
		"syncIntervalH": 1,
		"syncProducts": 1, "syncCustomers": 1, "syncSuppliers": 1, "syncOrders": 1,
		"syncSalesOrders": 1, "syncPurchasePrices": 1, "syncSalesPrices": 1,
		"pushOrdersToXentral": 1,
		"lastSyncProducts": 1, "lastSyncCustomers": 1, "lastSyncSuppliers": 1, "lastSyncOrders": 1,
		"lastSyncSalesOrders": 1, "lastSyncPurchasePrices": 1, "lastSyncSalesPrices": 1,
		"lastPushOrders": 1,
	}))
	if err != nil {
		return
	}
	var configs []models.XentralConfig
	cursor.All(ctx, &configs) //nolint

	engine := NewEngine(database)
	now := time.Now()

	for _, cfg := range configs {
		client := NewClient(cfg.BaseURL, cfg.APIToken)
		interval := time.Duration(cfg.SyncIntervalH) * time.Hour

		if cfg.SyncProducts && isDue(cfg.LastSyncProducts, now, interval) {
			engine.SyncProducts(ctx, cfg.TenantID, client) //nolint
			t := now
			database.XentralConfigs().UpdateOne(ctx, //nolint
				bson.M{"tenantId": cfg.TenantID},
				bson.M{"$set": bson.M{"lastSyncProducts": t}},
			)
		}
		if cfg.SyncCustomers && isDue(cfg.LastSyncCustomers, now, interval) {
			engine.SyncCustomers(ctx, cfg.TenantID, client) //nolint
			t := now
			database.XentralConfigs().UpdateOne(ctx, //nolint
				bson.M{"tenantId": cfg.TenantID},
				bson.M{"$set": bson.M{"lastSyncCustomers": t}},
			)
		}
		if cfg.SyncSuppliers && isDue(cfg.LastSyncSuppliers, now, interval) {
			engine.SyncSuppliers(ctx, cfg.TenantID, client) //nolint
			t := now
			database.XentralConfigs().UpdateOne(ctx, //nolint
				bson.M{"tenantId": cfg.TenantID},
				bson.M{"$set": bson.M{"lastSyncSuppliers": t}},
			)
		}
		if cfg.SyncOrders && isDue(cfg.LastSyncOrders, now, interval) {
			engine.SyncOrders(ctx, cfg.TenantID, client) //nolint
			t := now
			database.XentralConfigs().UpdateOne(ctx, //nolint
				bson.M{"tenantId": cfg.TenantID},
				bson.M{"$set": bson.M{"lastSyncOrders": t}},
			)
		}
		if cfg.SyncSalesOrders && isDue(cfg.LastSyncSalesOrders, now, interval) {
			engine.SyncSalesOrders(ctx, cfg.TenantID, client) //nolint
			t := now
			database.XentralConfigs().UpdateOne(ctx, //nolint
				bson.M{"tenantId": cfg.TenantID},
				bson.M{"$set": bson.M{"lastSyncSalesOrders": t}},
			)
		}
		if cfg.SyncPurchasePrices && isDue(cfg.LastSyncPurchasePrices, now, interval) {
			engine.SyncPurchasePrices(ctx, cfg.TenantID, client) //nolint
			t := now
			database.XentralConfigs().UpdateOne(ctx, //nolint
				bson.M{"tenantId": cfg.TenantID},
				bson.M{"$set": bson.M{"lastSyncPurchasePrices": t}},
			)
		}
		if cfg.SyncSalesPrices && isDue(cfg.LastSyncSalesPrices, now, interval) {
			engine.SyncSalesPrices(ctx, cfg.TenantID, client) //nolint
			t := now
			database.XentralConfigs().UpdateOne(ctx, //nolint
				bson.M{"tenantId": cfg.TenantID},
				bson.M{"$set": bson.M{"lastSyncSalesPrices": t}},
			)
		}
		if cfg.PushOrdersToXentral && isDue(cfg.LastPushOrders, now, interval) {
			engine.PushAllOrdersToXentral(ctx, cfg.TenantID, client) //nolint
			t := now
			database.XentralConfigs().UpdateOne(ctx, //nolint
				bson.M{"tenantId": cfg.TenantID},
				bson.M{"$set": bson.M{"lastPushOrders": t}},
			)
		}
		if cfg.SyncWarehouses && isDue(cfg.LastSyncWarehouses, now, interval) {
			engine.SyncWarehouses(ctx, cfg.TenantID, client) //nolint
			t := now
			database.XentralConfigs().UpdateOne(ctx, //nolint
				bson.M{"tenantId": cfg.TenantID},
				bson.M{"$set": bson.M{"lastSyncWarehouses": t}},
			)
		}
		if cfg.SyncStocks && isDue(cfg.LastSyncStocks, now, interval) {
			engine.SyncStocks(ctx, cfg.TenantID, client) //nolint
			t := now
			database.XentralConfigs().UpdateOne(ctx, //nolint
				bson.M{"tenantId": cfg.TenantID},
				bson.M{"$set": bson.M{"lastSyncStocks": t}},
			)
		}
	}
}

// -------------------------------------------------------------------
// Warehouses (Xentral /api/v1/warehouses + /api/v1/storageLocations → LastSaaS)
// -------------------------------------------------------------------

func (e *Engine) SyncWarehouses(ctx context.Context, tenantID primitive.ObjectID, client *Client) models.XentralSyncLog {
	log := e.startLog(ctx, tenantID, "warehouses")

	warehouses, err := client.ListWarehouses(ctx)
	if err != nil {
		return e.failLog(ctx, log, err.Error())
	}
	for _, w := range warehouses {
		if err := e.upsertWarehouse(ctx, tenantID, w); err != nil {
			log.Errors = append(log.Errors, fmt.Sprintf("%s: %v", w.ID, err))
			log.Skipped++
		} else {
			log.Updated++
		}
	}

	locations, err := client.ListStorageLocations(ctx)
	if err != nil {
		// Non-fatal: some installations don't have storage locations
		log.Errors = append(log.Errors, fmt.Sprintf("storage locations: %v", err))
	} else {
		for _, l := range locations {
			if err := e.upsertStorageLocation(ctx, tenantID, l); err != nil {
				log.Errors = append(log.Errors, fmt.Sprintf("loc %s: %v", l.ID, err))
				log.Skipped++
			} else {
				log.Updated++
			}
		}
	}

	return e.finishLog(ctx, log)
}

func (e *Engine) upsertWarehouse(ctx context.Context, tenantID primitive.ObjectID, xw XWarehouse) error {
	if xw.ID == "" {
		return nil
	}
	now := time.Now()
	result, err := e.db.Warehouses().UpdateOne(ctx,
		bson.M{"tenantId": tenantID, "xentralId": xw.ID},
		bson.M{"$set": bson.M{
			"name":      truncate(xw.Name, 100),
			"shortName": truncate(xw.ShortName, 20),
			"active":    xw.Active,
			"updatedAt": now,
		}, "$setOnInsert": bson.M{
			"tenantId":  tenantID,
			"xentralId": xw.ID,
			"createdAt": now,
		}},
		options.Update().SetUpsert(true),
	)
	_ = result
	return err
}

func (e *Engine) upsertStorageLocation(ctx context.Context, tenantID primitive.ObjectID, xl XStorageLocation) error {
	if xl.ID == "" {
		return nil
	}
	// Resolve parent warehouse ObjectID
	var wh struct {
		ID primitive.ObjectID `bson:"_id"`
	}
	warehouseFilter := bson.M{"tenantId": tenantID, "xentralId": xl.Warehouse.ID}
	if err := e.db.Warehouses().FindOne(ctx, warehouseFilter).Decode(&wh); err != nil {
		return fmt.Errorf("warehouse %s not found: %w", xl.Warehouse.ID, err)
	}
	now := time.Now()
	_, err := e.db.StorageLocations().UpdateOne(ctx,
		bson.M{"tenantId": tenantID, "xentralId": xl.ID},
		bson.M{"$set": bson.M{
			"name":        truncate(xl.Name, 100),
			"warehouseId": wh.ID,
			"aisle":       truncate(xl.Aisle, 20),
			"rack":        truncate(xl.Rack, 20),
			"level":       truncate(xl.Level, 20),
			"active":      xl.Active,
			"updatedAt":   now,
		}, "$setOnInsert": bson.M{
			"tenantId":  tenantID,
			"xentralId": xl.ID,
			"createdAt": now,
		}},
		options.Update().SetUpsert(true),
	)
	return err
}

// -------------------------------------------------------------------
// Stocks (Xentral /api/v1/stocks → LastSaaS StockLevel)
// -------------------------------------------------------------------

func (e *Engine) SyncStocks(ctx context.Context, tenantID primitive.ObjectID, client *Client) models.XentralSyncLog {
	log := e.startLog(ctx, tenantID, "stocks")

	stocks, err := client.ListProductStocks(ctx)
	if err != nil {
		return e.failLog(ctx, log, err.Error())
	}

	for _, s := range stocks {
		if err := e.upsertStockLevel(ctx, tenantID, s); err != nil {
			log.Errors = append(log.Errors, fmt.Sprintf("%s: %v", s.ID, err))
			log.Skipped++
		} else {
			log.Updated++
		}
	}

	return e.finishLog(ctx, log)
}

func (e *Engine) upsertStockLevel(ctx context.Context, tenantID primitive.ObjectID, xs XProductStock) error {
	if xs.ID == "" || xs.Article.ID == "" {
		return nil
	}
	productID := e.resolveProductID(ctx, tenantID, xs.Article.ID)
	if productID == nil {
		return nil // product not yet synced — skip silently
	}

	// Optionally resolve warehouse and storage location by Xentral ID.
	var warehouseID, locationID *primitive.ObjectID
	if xs.Warehouse.ID != "" {
		var wh struct {
			ID primitive.ObjectID `bson:"_id"`
		}
		if err := e.db.Warehouses().FindOne(ctx, bson.M{"tenantId": tenantID, "xentralId": xs.Warehouse.ID}).Decode(&wh); err == nil {
			warehouseID = &wh.ID
		}
	}
	if xs.StorageLocation.ID != "" {
		var loc struct {
			ID primitive.ObjectID `bson:"_id"`
		}
		if err := e.db.StorageLocations().FindOne(ctx, bson.M{"tenantId": tenantID, "xentralId": xs.StorageLocation.ID}).Decode(&loc); err == nil {
			locationID = &loc.ID
		}
	}

	now := time.Now()
	setFields := bson.M{
		"productId":   *productID,
		"quantity":    xs.Quantity,
		"unit":        xs.Unit,
		"xentralId":   xs.ID,
		"updatedAt":   now,
	}
	if warehouseID != nil {
		setFields["warehouseId"] = warehouseID
	}
	if locationID != nil {
		setFields["storageLocationId"] = locationID
	}
	if xs.Warehouse.Name != "" {
		setFields["location"] = xs.Warehouse.Name
	}

	_, err := e.db.StockLevels().UpdateOne(ctx,
		bson.M{"tenantId": tenantID, "xentralId": xs.ID},
		bson.M{"$set": setFields, "$setOnInsert": bson.M{"tenantId": tenantID, "createdAt": now}},
		options.Update().SetUpsert(true),
	)
	if err != nil {
		return err
	}

	// If the stock entry carries tracking info, also maintain an InventoryLot.
	if xs.SerialNumber != "" || xs.BatchNumber != "" || xs.BestBefore != "" {
		lot := models.InventoryLot{
			TenantID:          tenantID,
			ProductID:         *productID,
			ReceivedAt:        now,
			Quantity:          int(xs.Quantity),
			Remaining:         int(xs.Quantity),
			Source:            "xentral",
			SerialNumber:      xs.SerialNumber,
			BatchNumber:       xs.BatchNumber,
			WarehouseID:       warehouseID,
			StorageLocationID: locationID,
			XentralID:         xs.ID,
			CreatedAt:         now,
			UpdatedAt:         now,
		}
		if xs.BestBefore != "" {
			if t, err := time.Parse("2006-01-02", xs.BestBefore); err == nil {
				lot.ExpiresAt = &t
			}
		}
		_, _ = e.db.InventoryLots().UpdateOne(ctx,
			bson.M{"tenantId": tenantID, "xentralId": xs.ID},
			bson.M{"$set": bson.M{
				"quantity":          lot.Quantity,
				"remaining":         lot.Remaining,
				"serialNumber":      lot.SerialNumber,
				"batchNumber":       lot.BatchNumber,
				"expiresAt":         lot.ExpiresAt,
				"warehouseId":       lot.WarehouseID,
				"storageLocationId": lot.StorageLocationID,
				"updatedAt":         now,
			}, "$setOnInsert": bson.M{
				"tenantId":   tenantID,
				"productId":  *productID,
				"receivedAt": now,
				"source":     "xentral",
				"xentralId":  xs.ID,
				"unitEkEur":  0,
				"createdAt":  now,
			}},
			options.Update().SetUpsert(true),
		)
	}
	return nil
}

// -------------------------------------------------------------------
// Stocks per product (official /api/products/:id/stocks, v1-beta)
// -------------------------------------------------------------------

// SyncStocksPerProduct fetches stock levels using the official v1-beta endpoint
// GET /api/products/{id}/stocks and upserts one StockLevel record per warehouse
// per product. This is the recommended approach for the initial stock import.
//
// Prerequisites: warehouses must already be synced (SyncWarehouses) so that
// Xentral warehouse IDs can be resolved to local ObjectIDs.
func (e *Engine) SyncStocksPerProduct(ctx context.Context, tenantID primitive.ObjectID, client *Client) models.XentralSyncLog {
	log := e.startLog(ctx, tenantID, "stocks_per_product")

	// Collect all mapped products for this tenant.
	cursor, err := e.db.XentralMappings().Find(ctx, bson.M{"tenantId": tenantID, "entity": "product"})
	if err != nil {
		return e.failLog(ctx, log, "find product mappings: "+err.Error())
	}
	defer cursor.Close(ctx)

	for cursor.Next(ctx) {
		var mapping models.XentralMapping
		if err := cursor.Decode(&mapping); err != nil {
			log.Errors = append(log.Errors, "decode mapping: "+err.Error())
			log.Skipped++
			continue
		}

		summary, err := client.GetProductStockSummary(ctx, mapping.XentralID)
		if err != nil {
			log.Errors = append(log.Errors, mapping.XentralID+": "+err.Error())
			log.Skipped++
			continue
		}

		for _, wEntry := range summary.Warehouses {
			if err := e.upsertStockFromSummary(ctx, tenantID, mapping.LocalID, mapping.XentralID, wEntry); err != nil {
				log.Errors = append(log.Errors, mapping.XentralID+"#"+wEntry.ID+": "+err.Error())
				log.Skipped++
			} else {
				log.Updated++
			}
		}
	}
	if err := cursor.Err(); err != nil {
		log.Errors = append(log.Errors, "cursor: "+err.Error())
	}

	return e.finishLog(ctx, log)
}

// upsertStockFromSummary writes one StockLevel row for a product/warehouse pair
// from the per-product stock summary endpoint.
// Identity key: tenantId + xentralId (= "productXentralId#warehouseXentralId").
func (e *Engine) upsertStockFromSummary(
	ctx context.Context,
	tenantID primitive.ObjectID,
	productID primitive.ObjectID,
	xentralProductID string,
	wEntry XStockWarehouseEntry,
) error {
	// Resolve warehouse ObjectID (best-effort; falls back to no warehouseId).
	var warehouseID *primitive.ObjectID
	var wh struct {
		ID primitive.ObjectID `bson:"_id"`
	}
	if err := e.db.Warehouses().FindOne(ctx, bson.M{"tenantId": tenantID, "xentralId": wEntry.ID}).Decode(&wh); err == nil {
		warehouseID = &wh.ID
	}

	now := time.Now()
	xentralStockID := xentralProductID + "#" + wEntry.ID
	setFields := bson.M{
		"productId": productID,
		"quantity":  wEntry.Physical,
		"xentralId": xentralStockID,
		"updatedAt": now,
	}
	if warehouseID != nil {
		setFields["warehouseId"] = warehouseID
	}

	_, err := e.db.StockLevels().UpdateOne(ctx,
		bson.M{"tenantId": tenantID, "xentralId": xentralStockID},
		bson.M{"$set": setFields, "$setOnInsert": bson.M{"tenantId": tenantID, "createdAt": now}},
		options.Update().SetUpsert(true),
	)
	return err
}

func isDue(last *time.Time, now time.Time, interval time.Duration) bool {
	if last == nil {
		return true
	}
	return now.Sub(*last) >= interval
}

// -------------------------------------------------------------------
// Helpers
// -------------------------------------------------------------------

// startLog marks any pre-existing "running" logs for the given entity+tenant
// as aborted, then inserts a fresh "running" log and returns it.
// This ensures stale "running" entries (e.g. from a previously cancelled sync)
// are always resolved before a new run begins.
func (e *Engine) startLog(ctx context.Context, tenantID primitive.ObjectID, entity string) models.XentralSyncLog {
	now := time.Now()
	writeCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	e.db.XentralSyncLogs().UpdateMany(writeCtx, //nolint
		bson.M{"tenantId": tenantID, "entity": entity, "status": "running"},
		bson.M{"$set": bson.M{
			"status":     "error",
			"errors":     []string{"Abgebrochen (neuer Sync gestartet)"},
			"finishedAt": now,
		}},
	)
	log := models.XentralSyncLog{
		ID:        primitive.NewObjectID(),
		TenantID:  tenantID,
		Entity:    entity,
		Status:    "running",
		StartedAt: now,
	}
	e.db.XentralSyncLogs().InsertOne(writeCtx, log) //nolint
	return log
}

func (e *Engine) failLog(ctx context.Context, log models.XentralSyncLog, errMsg string) models.XentralSyncLog {
	now := time.Now()
	log.Status = "error"
	log.Errors = []string{errMsg}
	log.FinishedAt = &now
	// Use a fresh context so the log update is never blocked by a cancelled request context.
	writeCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	e.db.XentralSyncLogs().UpdateOne(writeCtx, //nolint
		bson.M{"_id": log.ID},
		bson.M{"$set": bson.M{"status": log.Status, "errors": log.Errors, "finishedAt": log.FinishedAt}},
	)
	return log
}

func (e *Engine) finishLog(ctx context.Context, log models.XentralSyncLog) models.XentralSyncLog {
	now := time.Now()
	log.Status = "success"
	if len(log.Errors) > 0 {
		log.Status = "partial"
	}
	log.FinishedAt = &now
	// Use a fresh context so the log update is never blocked by a cancelled request context.
	writeCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	e.db.XentralSyncLogs().UpdateOne(writeCtx, //nolint
		bson.M{"_id": log.ID},
		bson.M{"$set": bson.M{
			"status":     log.Status,
			"created":    log.Created,
			"updated":    log.Updated,
			"skipped":    log.Skipped,
			"errors":     log.Errors,
			"finishedAt": log.FinishedAt,
		}},
	)
	_ = ctx // context was used for the sync work; log write uses its own context above
	return log
}

// Truncate is the exported version used by the handlers package.
func Truncate(s string, max int) string {
	if len(s) <= max {
		return s
	}
	return s[:max]
}

func truncate(s string, max int) string { return Truncate(s, max) }

// resolveTagNames extracts the Name field from XTag objects returned by Xentral.
// Empty names are dropped.
func resolveTagNames(tags []XTag) []string {
	if len(tags) == 0 {
		return nil
	}
	out := make([]string, 0, len(tags))
	for _, t := range tags {
		if t.Name != "" {
			out = append(out, t.Name)
		}
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

// resolveAttributes converts Xentral characteristics into ProductAttribute structs.
// Entries without a name are skipped. Value and Unit are truncated to model limits.
func resolveAttributes(chars []XCharacteristic) []models.ProductAttribute {
	if len(chars) == 0 {
		return nil
	}
	out := make([]models.ProductAttribute, 0, len(chars))
	for _, c := range chars {
		if c.Name == "" {
			continue
		}
		out = append(out, models.ProductAttribute{
			Key:   truncate(c.Name, 100),
			Value: truncate(c.Value, 500),
			Unit:  truncate(c.Unit, 30),
		})
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

// resolveFreeFields converts XV2FreeField entries from the v2 products API into
// ProductFreeField model objects, skipping entries without a value.
// The name is taken from the non-null Name pointer; entries with null name are kept
// if they have a value (using empty string as name in that case).
func resolveFreeFields(fields []XV2FreeField) []models.ProductFreeField {
	if len(fields) == 0 {
		return nil
	}
	out := make([]models.ProductFreeField, 0, len(fields))
	for _, f := range fields {
		if f.Value == "" {
			continue
		}
		name := ""
		if f.Name != nil {
			name = *f.Name
		}
		out = append(out, models.ProductFreeField{
			ID:    f.ID,
			Name:  truncate(name, 255),
			Value: truncate(f.Value, 500),
		})
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

// mapFreifelderToUserDefs maps Xentral freifeld1..10 directly to UserDef01..10 (1:1).
// Used for orders and sales orders (v1/v3 API still uses flat freifeld fields).
func mapFreifelderToUserDefs(freifelder map[string]string) [10]string {
	var result [10]string
	for i := range result {
		key := fmt.Sprintf("freifeld%d", i+1)
		if v, ok := freifelder[key]; ok {
			result[i] = truncate(v, 255)
		}
	}
	return result
}
