package handlers

// countrySeedData contains all ISO 3166-1 countries with standard metadata.
// Fields: name, iso2, iso3, isoNumeric, currency, currencyCode, currencySymbol, phoneCode, region, capital
type countrySeed struct {
	Name           string
	ISO2           string
	ISO3           string
	ISONumeric     string
	Currency       string
	CurrencyCode   string
	CurrencySymbol string
	PhoneCode      string
	Region         string
	Capital        string
}

var allCountries = []countrySeed{
	{"Afghanistan", "AF", "AFG", "004", "Afghan Afghani", "AFN", "؋", "+93", "Asia", "Kabul"},
	{"Albania", "AL", "ALB", "008", "Albanian Lek", "ALL", "L", "+355", "Europe", "Tirana"},
	{"Algeria", "DZ", "DZA", "012", "Algerian Dinar", "DZD", "د.ج", "+213", "Africa", "Algiers"},
	{"Andorra", "AD", "AND", "020", "Euro", "EUR", "€", "+376", "Europe", "Andorra la Vella"},
	{"Angola", "AO", "AGO", "024", "Angolan Kwanza", "AOA", "Kz", "+244", "Africa", "Luanda"},
	{"Antigua and Barbuda", "AG", "ATG", "028", "East Caribbean Dollar", "XCD", "$", "+1-268", "Americas", "Saint John's"},
	{"Argentina", "AR", "ARG", "032", "Argentine Peso", "ARS", "$", "+54", "Americas", "Buenos Aires"},
	{"Armenia", "AM", "ARM", "051", "Armenian Dram", "AMD", "֏", "+374", "Asia", "Yerevan"},
	{"Australia", "AU", "AUS", "036", "Australian Dollar", "AUD", "$", "+61", "Oceania", "Canberra"},
	{"Austria", "AT", "AUT", "040", "Euro", "EUR", "€", "+43", "Europe", "Vienna"},
	{"Azerbaijan", "AZ", "AZE", "031", "Azerbaijani Manat", "AZN", "₼", "+994", "Asia", "Baku"},
	{"Bahamas", "BS", "BHS", "044", "Bahamian Dollar", "BSD", "$", "+1-242", "Americas", "Nassau"},
	{"Bahrain", "BH", "BHR", "048", "Bahraini Dinar", "BHD", ".د.ب", "+973", "Asia", "Manama"},
	{"Bangladesh", "BD", "BGD", "050", "Bangladeshi Taka", "BDT", "৳", "+880", "Asia", "Dhaka"},
	{"Barbados", "BB", "BRB", "052", "Barbadian Dollar", "BBD", "$", "+1-246", "Americas", "Bridgetown"},
	{"Belarus", "BY", "BLR", "112", "Belarusian Ruble", "BYN", "Br", "+375", "Europe", "Minsk"},
	{"Belgium", "BE", "BEL", "056", "Euro", "EUR", "€", "+32", "Europe", "Brussels"},
	{"Belize", "BZ", "BLZ", "084", "Belize Dollar", "BZD", "$", "+501", "Americas", "Belmopan"},
	{"Benin", "BJ", "BEN", "204", "West African CFA Franc", "XOF", "Fr", "+229", "Africa", "Porto-Novo"},
	{"Bhutan", "BT", "BTN", "064", "Bhutanese Ngultrum", "BTN", "Nu", "+975", "Asia", "Thimphu"},
	{"Bolivia", "BO", "BOL", "068", "Bolivian Boliviano", "BOB", "Bs.", "+591", "Americas", "Sucre"},
	{"Bosnia and Herzegovina", "BA", "BIH", "070", "Bosnia-Herzegovina Convertible Mark", "BAM", "KM", "+387", "Europe", "Sarajevo"},
	{"Botswana", "BW", "BWA", "072", "Botswanan Pula", "BWP", "P", "+267", "Africa", "Gaborone"},
	{"Brazil", "BR", "BRA", "076", "Brazilian Real", "BRL", "R$", "+55", "Americas", "Brasília"},
	{"Brunei", "BN", "BRN", "096", "Brunei Dollar", "BND", "$", "+673", "Asia", "Bandar Seri Begawan"},
	{"Bulgaria", "BG", "BGR", "100", "Bulgarian Lev", "BGN", "лв", "+359", "Europe", "Sofia"},
	{"Burkina Faso", "BF", "BFA", "854", "West African CFA Franc", "XOF", "Fr", "+226", "Africa", "Ouagadougou"},
	{"Burundi", "BI", "BDI", "108", "Burundian Franc", "BIF", "Fr", "+257", "Africa", "Gitega"},
	{"Cabo Verde", "CV", "CPV", "132", "Cape Verdean Escudo", "CVE", "$", "+238", "Africa", "Praia"},
	{"Cambodia", "KH", "KHM", "116", "Cambodian Riel", "KHR", "៛", "+855", "Asia", "Phnom Penh"},
	{"Cameroon", "CM", "CMR", "120", "Central African CFA Franc", "XAF", "Fr", "+237", "Africa", "Yaoundé"},
	{"Canada", "CA", "CAN", "124", "Canadian Dollar", "CAD", "$", "+1", "Americas", "Ottawa"},
	{"Central African Republic", "CF", "CAF", "140", "Central African CFA Franc", "XAF", "Fr", "+236", "Africa", "Bangui"},
	{"Chad", "TD", "TCD", "148", "Central African CFA Franc", "XAF", "Fr", "+235", "Africa", "N'Djamena"},
	{"Chile", "CL", "CHL", "152", "Chilean Peso", "CLP", "$", "+56", "Americas", "Santiago"},
	{"China", "CN", "CHN", "156", "Chinese Yuan", "CNY", "¥", "+86", "Asia", "Beijing"},
	{"Colombia", "CO", "COL", "170", "Colombian Peso", "COP", "$", "+57", "Americas", "Bogotá"},
	{"Comoros", "KM", "COM", "174", "Comorian Franc", "KMF", "Fr", "+269", "Africa", "Moroni"},
	{"Congo (Brazzaville)", "CG", "COG", "178", "Central African CFA Franc", "XAF", "Fr", "+242", "Africa", "Brazzaville"},
	{"Congo (Kinshasa)", "CD", "COD", "180", "Congolese Franc", "CDF", "Fr", "+243", "Africa", "Kinshasa"},
	{"Costa Rica", "CR", "CRI", "188", "Costa Rican Colón", "CRC", "₡", "+506", "Americas", "San José"},
	{"Croatia", "HR", "HRV", "191", "Euro", "EUR", "€", "+385", "Europe", "Zagreb"},
	{"Cuba", "CU", "CUB", "192", "Cuban Peso", "CUP", "$", "+53", "Americas", "Havana"},
	{"Cyprus", "CY", "CYP", "196", "Euro", "EUR", "€", "+357", "Europe", "Nicosia"},
	{"Czech Republic", "CZ", "CZE", "203", "Czech Koruna", "CZK", "Kč", "+420", "Europe", "Prague"},
	{"Denmark", "DK", "DNK", "208", "Danish Krone", "DKK", "kr", "+45", "Europe", "Copenhagen"},
	{"Djibouti", "DJ", "DJI", "262", "Djiboutian Franc", "DJF", "Fr", "+253", "Africa", "Djibouti"},
	{"Dominica", "DM", "DMA", "212", "East Caribbean Dollar", "XCD", "$", "+1-767", "Americas", "Roseau"},
	{"Dominican Republic", "DO", "DOM", "214", "Dominican Peso", "DOP", "RD$", "+1-809", "Americas", "Santo Domingo"},
	{"Ecuador", "EC", "ECU", "218", "United States Dollar", "USD", "$", "+593", "Americas", "Quito"},
	{"Egypt", "EG", "EGY", "818", "Egyptian Pound", "EGP", "£", "+20", "Africa", "Cairo"},
	{"El Salvador", "SV", "SLV", "222", "United States Dollar", "USD", "$", "+503", "Americas", "San Salvador"},
	{"Equatorial Guinea", "GQ", "GNQ", "226", "Central African CFA Franc", "XAF", "Fr", "+240", "Africa", "Malabo"},
	{"Eritrea", "ER", "ERI", "232", "Eritrean Nakfa", "ERN", "Nfk", "+291", "Africa", "Asmara"},
	{"Estonia", "EE", "EST", "233", "Euro", "EUR", "€", "+372", "Europe", "Tallinn"},
	{"Eswatini", "SZ", "SWZ", "748", "Swazi Lilangeni", "SZL", "L", "+268", "Africa", "Mbabane"},
	{"Ethiopia", "ET", "ETH", "231", "Ethiopian Birr", "ETB", "Br", "+251", "Africa", "Addis Ababa"},
	{"Fiji", "FJ", "FJI", "242", "Fijian Dollar", "FJD", "$", "+679", "Oceania", "Suva"},
	{"Finland", "FI", "FIN", "246", "Euro", "EUR", "€", "+358", "Europe", "Helsinki"},
	{"France", "FR", "FRA", "250", "Euro", "EUR", "€", "+33", "Europe", "Paris"},
	{"Gabon", "GA", "GAB", "266", "Central African CFA Franc", "XAF", "Fr", "+241", "Africa", "Libreville"},
	{"Gambia", "GM", "GMB", "270", "Gambian Dalasi", "GMD", "D", "+220", "Africa", "Banjul"},
	{"Georgia", "GE", "GEO", "268", "Georgian Lari", "GEL", "₾", "+995", "Asia", "Tbilisi"},
	{"Germany", "DE", "DEU", "276", "Euro", "EUR", "€", "+49", "Europe", "Berlin"},
	{"Ghana", "GH", "GHA", "288", "Ghanaian Cedi", "GHS", "₵", "+233", "Africa", "Accra"},
	{"Greece", "GR", "GRC", "300", "Euro", "EUR", "€", "+30", "Europe", "Athens"},
	{"Grenada", "GD", "GRD", "308", "East Caribbean Dollar", "XCD", "$", "+1-473", "Americas", "Saint George's"},
	{"Guatemala", "GT", "GTM", "320", "Guatemalan Quetzal", "GTQ", "Q", "+502", "Americas", "Guatemala City"},
	{"Guinea", "GN", "GIN", "324", "Guinean Franc", "GNF", "Fr", "+224", "Africa", "Conakry"},
	{"Guinea-Bissau", "GW", "GNB", "624", "West African CFA Franc", "XOF", "Fr", "+245", "Africa", "Bissau"},
	{"Guyana", "GY", "GUY", "328", "Guyanese Dollar", "GYD", "$", "+592", "Americas", "Georgetown"},
	{"Haiti", "HT", "HTI", "332", "Haitian Gourde", "HTG", "G", "+509", "Americas", "Port-au-Prince"},
	{"Honduras", "HN", "HND", "340", "Honduran Lempira", "HNL", "L", "+504", "Americas", "Tegucigalpa"},
	{"Hungary", "HU", "HUN", "348", "Hungarian Forint", "HUF", "Ft", "+36", "Europe", "Budapest"},
	{"Iceland", "IS", "ISL", "352", "Icelandic Króna", "ISK", "kr", "+354", "Europe", "Reykjavík"},
	{"India", "IN", "IND", "356", "Indian Rupee", "INR", "₹", "+91", "Asia", "New Delhi"},
	{"Indonesia", "ID", "IDN", "360", "Indonesian Rupiah", "IDR", "Rp", "+62", "Asia", "Jakarta"},
	{"Iran", "IR", "IRN", "364", "Iranian Rial", "IRR", "﷼", "+98", "Asia", "Tehran"},
	{"Iraq", "IQ", "IRQ", "368", "Iraqi Dinar", "IQD", "ع.د", "+964", "Asia", "Baghdad"},
	{"Ireland", "IE", "IRL", "372", "Euro", "EUR", "€", "+353", "Europe", "Dublin"},
	{"Israel", "IL", "ISR", "376", "Israeli New Shekel", "ILS", "₪", "+972", "Asia", "Jerusalem"},
	{"Italy", "IT", "ITA", "380", "Euro", "EUR", "€", "+39", "Europe", "Rome"},
	{"Jamaica", "JM", "JAM", "388", "Jamaican Dollar", "JMD", "$", "+1-876", "Americas", "Kingston"},
	{"Japan", "JP", "JPN", "392", "Japanese Yen", "JPY", "¥", "+81", "Asia", "Tokyo"},
	{"Jordan", "JO", "JOR", "400", "Jordanian Dinar", "JOD", "د.ا", "+962", "Asia", "Amman"},
	{"Kazakhstan", "KZ", "KAZ", "398", "Kazakhstani Tenge", "KZT", "₸", "+7", "Asia", "Nur-Sultan"},
	{"Kenya", "KE", "KEN", "404", "Kenyan Shilling", "KES", "Ksh", "+254", "Africa", "Nairobi"},
	{"Kiribati", "KI", "KIR", "296", "Australian Dollar", "AUD", "$", "+686", "Oceania", "South Tarawa"},
	{"Korea, North", "KP", "PRK", "408", "North Korean Won", "KPW", "₩", "+850", "Asia", "Pyongyang"},
	{"Korea, South", "KR", "KOR", "410", "South Korean Won", "KRW", "₩", "+82", "Asia", "Seoul"},
	{"Kosovo", "XK", "XKX", "---", "Euro", "EUR", "€", "+383", "Europe", "Pristina"},
	{"Kuwait", "KW", "KWT", "414", "Kuwaiti Dinar", "KWD", "د.ك", "+965", "Asia", "Kuwait City"},
	{"Kyrgyzstan", "KG", "KGZ", "417", "Kyrgyzstani Som", "KGS", "с", "+996", "Asia", "Bishkek"},
	{"Laos", "LA", "LAO", "418", "Lao Kip", "LAK", "₭", "+856", "Asia", "Vientiane"},
	{"Latvia", "LV", "LVA", "428", "Euro", "EUR", "€", "+371", "Europe", "Riga"},
	{"Lebanon", "LB", "LBN", "422", "Lebanese Pound", "LBP", "ل.ل", "+961", "Asia", "Beirut"},
	{"Lesotho", "LS", "LSO", "426", "Lesotho Loti", "LSL", "L", "+266", "Africa", "Maseru"},
	{"Liberia", "LR", "LBR", "430", "Liberian Dollar", "LRD", "$", "+231", "Africa", "Monrovia"},
	{"Libya", "LY", "LBY", "434", "Libyan Dinar", "LYD", "ل.د", "+218", "Africa", "Tripoli"},
	{"Liechtenstein", "LI", "LIE", "438", "Swiss Franc", "CHF", "Fr", "+423", "Europe", "Vaduz"},
	{"Lithuania", "LT", "LTU", "440", "Euro", "EUR", "€", "+370", "Europe", "Vilnius"},
	{"Luxembourg", "LU", "LUX", "442", "Euro", "EUR", "€", "+352", "Europe", "Luxembourg"},
	{"Madagascar", "MG", "MDG", "450", "Malagasy Ariary", "MGA", "Ar", "+261", "Africa", "Antananarivo"},
	{"Malawi", "MW", "MWI", "454", "Malawian Kwacha", "MWK", "MK", "+265", "Africa", "Lilongwe"},
	{"Malaysia", "MY", "MYS", "458", "Malaysian Ringgit", "MYR", "RM", "+60", "Asia", "Kuala Lumpur"},
	{"Maldives", "MV", "MDV", "462", "Maldivian Rufiyaa", "MVR", "Rf", "+960", "Asia", "Malé"},
	{"Mali", "ML", "MLI", "466", "West African CFA Franc", "XOF", "Fr", "+223", "Africa", "Bamako"},
	{"Malta", "MT", "MLT", "470", "Euro", "EUR", "€", "+356", "Europe", "Valletta"},
	{"Marshall Islands", "MH", "MHL", "584", "United States Dollar", "USD", "$", "+692", "Oceania", "Majuro"},
	{"Mauritania", "MR", "MRT", "478", "Mauritanian Ouguiya", "MRU", "UM", "+222", "Africa", "Nouakchott"},
	{"Mauritius", "MU", "MUS", "480", "Mauritian Rupee", "MUR", "₨", "+230", "Africa", "Port Louis"},
	{"Mexico", "MX", "MEX", "484", "Mexican Peso", "MXN", "$", "+52", "Americas", "Mexico City"},
	{"Micronesia", "FM", "FSM", "583", "United States Dollar", "USD", "$", "+691", "Oceania", "Palikir"},
	{"Moldova", "MD", "MDA", "498", "Moldovan Leu", "MDL", "L", "+373", "Europe", "Chișinău"},
	{"Monaco", "MC", "MCO", "492", "Euro", "EUR", "€", "+377", "Europe", "Monaco"},
	{"Mongolia", "MN", "MNG", "496", "Mongolian Tögrög", "MNT", "₮", "+976", "Asia", "Ulaanbaatar"},
	{"Montenegro", "ME", "MNE", "499", "Euro", "EUR", "€", "+382", "Europe", "Podgorica"},
	{"Morocco", "MA", "MAR", "504", "Moroccan Dirham", "MAD", "د.م.", "+212", "Africa", "Rabat"},
	{"Mozambique", "MZ", "MOZ", "508", "Mozambican Metical", "MZN", "MT", "+258", "Africa", "Maputo"},
	{"Myanmar", "MM", "MMR", "104", "Myanmar Kyat", "MMK", "K", "+95", "Asia", "Naypyidaw"},
	{"Namibia", "NA", "NAM", "516", "Namibian Dollar", "NAD", "$", "+264", "Africa", "Windhoek"},
	{"Nauru", "NR", "NRU", "520", "Australian Dollar", "AUD", "$", "+674", "Oceania", "Yaren"},
	{"Nepal", "NP", "NPL", "524", "Nepalese Rupee", "NPR", "₨", "+977", "Asia", "Kathmandu"},
	{"Netherlands", "NL", "NLD", "528", "Euro", "EUR", "€", "+31", "Europe", "Amsterdam"},
	{"New Zealand", "NZ", "NZL", "554", "New Zealand Dollar", "NZD", "$", "+64", "Oceania", "Wellington"},
	{"Nicaragua", "NI", "NIC", "558", "Nicaraguan Córdoba", "NIO", "C$", "+505", "Americas", "Managua"},
	{"Niger", "NE", "NER", "562", "West African CFA Franc", "XOF", "Fr", "+227", "Africa", "Niamey"},
	{"Nigeria", "NG", "NGA", "566", "Nigerian Naira", "NGN", "₦", "+234", "Africa", "Abuja"},
	{"North Macedonia", "MK", "MKD", "807", "Macedonian Denar", "MKD", "ден", "+389", "Europe", "Skopje"},
	{"Norway", "NO", "NOR", "578", "Norwegian Krone", "NOK", "kr", "+47", "Europe", "Oslo"},
	{"Oman", "OM", "OMN", "512", "Omani Rial", "OMR", "ر.ع.", "+968", "Asia", "Muscat"},
	{"Pakistan", "PK", "PAK", "586", "Pakistani Rupee", "PKR", "₨", "+92", "Asia", "Islamabad"},
	{"Palau", "PW", "PLW", "585", "United States Dollar", "USD", "$", "+680", "Oceania", "Ngerulmud"},
	{"Palestine", "PS", "PSE", "275", "Israeli New Shekel", "ILS", "₪", "+970", "Asia", "Ramallah"},
	{"Panama", "PA", "PAN", "591", "Panamanian Balboa", "PAB", "B/.", "+507", "Americas", "Panama City"},
	{"Papua New Guinea", "PG", "PNG", "598", "Papua New Guinean Kina", "PGK", "K", "+675", "Oceania", "Port Moresby"},
	{"Paraguay", "PY", "PRY", "600", "Paraguayan Guaraní", "PYG", "₲", "+595", "Americas", "Asunción"},
	{"Peru", "PE", "PER", "604", "Peruvian Sol", "PEN", "S/.", "+51", "Americas", "Lima"},
	{"Philippines", "PH", "PHL", "608", "Philippine Peso", "PHP", "₱", "+63", "Asia", "Manila"},
	{"Poland", "PL", "POL", "616", "Polish Złoty", "PLN", "zł", "+48", "Europe", "Warsaw"},
	{"Portugal", "PT", "PRT", "620", "Euro", "EUR", "€", "+351", "Europe", "Lisbon"},
	{"Qatar", "QA", "QAT", "634", "Qatari Riyal", "QAR", "ر.ق", "+974", "Asia", "Doha"},
	{"Romania", "RO", "ROU", "642", "Romanian Leu", "RON", "lei", "+40", "Europe", "Bucharest"},
	{"Russia", "RU", "RUS", "643", "Russian Ruble", "RUB", "₽", "+7", "Europe", "Moscow"},
	{"Rwanda", "RW", "RWA", "646", "Rwandan Franc", "RWF", "Fr", "+250", "Africa", "Kigali"},
	{"Saint Kitts and Nevis", "KN", "KNA", "659", "East Caribbean Dollar", "XCD", "$", "+1-869", "Americas", "Basseterre"},
	{"Saint Lucia", "LC", "LCA", "662", "East Caribbean Dollar", "XCD", "$", "+1-758", "Americas", "Castries"},
	{"Saint Vincent and the Grenadines", "VC", "VCT", "670", "East Caribbean Dollar", "XCD", "$", "+1-784", "Americas", "Kingstown"},
	{"Samoa", "WS", "WSM", "882", "Samoan Tālā", "WST", "T", "+685", "Oceania", "Apia"},
	{"San Marino", "SM", "SMR", "674", "Euro", "EUR", "€", "+378", "Europe", "City of San Marino"},
	{"São Tomé and Príncipe", "ST", "STP", "678", "São Tomé and Príncipe Dobra", "STN", "Db", "+239", "Africa", "São Tomé"},
	{"Saudi Arabia", "SA", "SAU", "682", "Saudi Riyal", "SAR", "ر.س", "+966", "Asia", "Riyadh"},
	{"Senegal", "SN", "SEN", "686", "West African CFA Franc", "XOF", "Fr", "+221", "Africa", "Dakar"},
	{"Serbia", "RS", "SRB", "688", "Serbian Dinar", "RSD", "дин", "+381", "Europe", "Belgrade"},
	{"Seychelles", "SC", "SYC", "690", "Seychellois Rupee", "SCR", "₨", "+248", "Africa", "Victoria"},
	{"Sierra Leone", "SL", "SLE", "694", "Sierra Leonean Leone", "SLL", "Le", "+232", "Africa", "Freetown"},
	{"Singapore", "SG", "SGP", "702", "Singapore Dollar", "SGD", "$", "+65", "Asia", "Singapore"},
	{"Slovakia", "SK", "SVK", "703", "Euro", "EUR", "€", "+421", "Europe", "Bratislava"},
	{"Slovenia", "SI", "SVN", "705", "Euro", "EUR", "€", "+386", "Europe", "Ljubljana"},
	{"Solomon Islands", "SB", "SLB", "090", "Solomon Islands Dollar", "SBD", "$", "+677", "Oceania", "Honiara"},
	{"Somalia", "SO", "SOM", "706", "Somali Shilling", "SOS", "Sh", "+252", "Africa", "Mogadishu"},
	{"South Africa", "ZA", "ZAF", "710", "South African Rand", "ZAR", "R", "+27", "Africa", "Pretoria"},
	{"South Sudan", "SS", "SSD", "728", "South Sudanese Pound", "SSP", "£", "+211", "Africa", "Juba"},
	{"Spain", "ES", "ESP", "724", "Euro", "EUR", "€", "+34", "Europe", "Madrid"},
	{"Sri Lanka", "LK", "LKA", "144", "Sri Lankan Rupee", "LKR", "₨", "+94", "Asia", "Colombo"},
	{"Sudan", "SD", "SDN", "729", "Sudanese Pound", "SDG", "ج.س.", "+249", "Africa", "Khartoum"},
	{"Suriname", "SR", "SUR", "740", "Surinamese Dollar", "SRD", "$", "+597", "Americas", "Paramaribo"},
	{"Sweden", "SE", "SWE", "752", "Swedish Krona", "SEK", "kr", "+46", "Europe", "Stockholm"},
	{"Switzerland", "CH", "CHE", "756", "Swiss Franc", "CHF", "Fr", "+41", "Europe", "Bern"},
	{"Syria", "SY", "SYR", "760", "Syrian Pound", "SYP", "£", "+963", "Asia", "Damascus"},
	{"Taiwan", "TW", "TWN", "158", "New Taiwan Dollar", "TWD", "$", "+886", "Asia", "Taipei"},
	{"Tajikistan", "TJ", "TJK", "762", "Tajikistani Somoni", "TJS", "SM", "+992", "Asia", "Dushanbe"},
	{"Tanzania", "TZ", "TZA", "834", "Tanzanian Shilling", "TZS", "Sh", "+255", "Africa", "Dodoma"},
	{"Thailand", "TH", "THA", "764", "Thai Baht", "THB", "฿", "+66", "Asia", "Bangkok"},
	{"Timor-Leste", "TL", "TLS", "626", "United States Dollar", "USD", "$", "+670", "Asia", "Dili"},
	{"Togo", "TG", "TGO", "768", "West African CFA Franc", "XOF", "Fr", "+228", "Africa", "Lomé"},
	{"Tonga", "TO", "TON", "776", "Tongan Paʻanga", "TOP", "T$", "+676", "Oceania", "Nukuʻalofa"},
	{"Trinidad and Tobago", "TT", "TTO", "780", "Trinidad and Tobago Dollar", "TTD", "$", "+1-868", "Americas", "Port of Spain"},
	{"Tunisia", "TN", "TUN", "788", "Tunisian Dinar", "TND", "د.ت", "+216", "Africa", "Tunis"},
	{"Turkey", "TR", "TUR", "792", "Turkish Lira", "TRY", "₺", "+90", "Europe", "Ankara"},
	{"Turkmenistan", "TM", "TKM", "795", "Turkmenistani Manat", "TMT", "T", "+993", "Asia", "Ashgabat"},
	{"Tuvalu", "TV", "TUV", "798", "Australian Dollar", "AUD", "$", "+688", "Oceania", "Funafuti"},
	{"Uganda", "UG", "UGA", "800", "Ugandan Shilling", "UGX", "Sh", "+256", "Africa", "Kampala"},
	{"Ukraine", "UA", "UKR", "804", "Ukrainian Hryvnia", "UAH", "₴", "+380", "Europe", "Kyiv"},
	{"United Arab Emirates", "AE", "ARE", "784", "UAE Dirham", "AED", "د.إ", "+971", "Asia", "Abu Dhabi"},
	{"United Kingdom", "GB", "GBR", "826", "British Pound", "GBP", "£", "+44", "Europe", "London"},
	{"United States", "US", "USA", "840", "United States Dollar", "USD", "$", "+1", "Americas", "Washington D.C."},
	{"Uruguay", "UY", "URY", "858", "Uruguayan Peso", "UYU", "$", "+598", "Americas", "Montevideo"},
	{"Uzbekistan", "UZ", "UZB", "860", "Uzbekistani Som", "UZS", "so'm", "+998", "Asia", "Tashkent"},
	{"Vanuatu", "VU", "VUT", "548", "Vanuatu Vatu", "VUV", "Vt", "+678", "Oceania", "Port Vila"},
	{"Vatican City", "VA", "VAT", "336", "Euro", "EUR", "€", "+379", "Europe", "Vatican City"},
	{"Venezuela", "VE", "VEN", "862", "Venezuelan Bolívar", "VES", "Bs.S", "+58", "Americas", "Caracas"},
	{"Vietnam", "VN", "VNM", "704", "Vietnamese Đồng", "VND", "₫", "+84", "Asia", "Hanoi"},
	{"Yemen", "YE", "YEM", "887", "Yemeni Rial", "YER", "﷼", "+967", "Asia", "Sana'a"},
	{"Zambia", "ZM", "ZMB", "894", "Zambian Kwacha", "ZMW", "ZK", "+260", "Africa", "Lusaka"},
	{"Zimbabwe", "ZW", "ZWE", "716", "Zimbabwean Dollar", "ZWL", "$", "+263", "Africa", "Harare"},
}
